CREATE TABLE PRODUCTS_OUTPUT_DETAILS
(
IDPRODUCTS_OUTPUT INT NOT NULL,
IDPRODUCTS INT NOT NULL,
PRECO FLOAT NOT NULL,
QUANTIDADE INT NOT NULL,
PRIMARY KEY (IDPRODUCTS_OUTPUT,IDPRODUCTS),
CONSTRAINT [FK_PRODUCTS_OUTPUT_DETAILS_PRODUCTS_OUTPUT] FOREIGN KEY (IDPRODUCTS_OUTPUT) REFERENCES PRODUCTS_OUTPUT,
CONSTRAINT [FK_PRODUCTS_OUTPUT_DETAILS_PRODUCTS] FOREIGN KEY (IDPRODUCTS) REFERENCES PRODUCTS

)