CREATE TABLE ROOMS_TYPE
(
ID INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(100) NOT NULL,
VALOR FLOAT NOT NULL,
VALORDIARIA FLOAT NOT NULL,
QTDHOSPEDES INT NOT NULL
)

CREATE TABLE ROOMS
(
ID INT PRIMARY KEY IDENTITY,
ISOCUPADO BIT NOT NULL,
NUMEROQUARTO VARCHAR(5) NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
IDROOMS_TYPE INT NOT NULL,
CONSTRAINT FK_ROOMS_ROOMSTYPE FOREIGN KEY (IDROOMS_TYPE)
REFERENCES ROOMS_TYPE
)

CREATE TABLE ROOMS_CLIENTS
(
IDROOMS INT NOT NULL,
IDCLIENTS INT NOT NULL,
CONSTRAINT FK_ROOMS_CLIENTS_ROOMS FOREIGN KEY (IDROOMS)
REFERENCES ROOMS,
CONSTRAINT FK_ROOMS_CLIENTS_CLIENTS FOREIGN KEY (IDCLIENTS)
REFERENCES CLIENTS,
PRIMARY KEY(IDROOMS, IDCLIENTS)
)

CREATE TABLE CHECKIN_CLIENTS
(
ID INT PRIMARY KEY IDENTITY,
DATAENTRADA DATETIME DEFAULT GETDATE() NOT NULL,
PREVISAOSAIDA DATETIME NOT NULL,
IDCLIENTS INT NOT NULL,
IDROOMS INT NOT NULL,
IDEMPLOYEES INT NOT NULL,
CONSTRAINT FK_CHECKIN_CLIENTS_CLIENTS FOREIGN KEY (IDCLIENTS)
REFERENCES CLIENTS,
CONSTRAINT FK_CHECKIN_CLIENTS_ROOMS FOREIGN KEY (IDROOMS)
REFERENCES ROOMS,
CONSTRAINT FK_CHECKIN_CLIENTS_EMPLOYEES FOREIGN KEY (IDEMPLOYEES)
REFERENCES EMPLOYEES
)

CREATE TABLE CHECKOUT_CLIENTS
(
ID INT PRIMARY KEY IDENTITY,
DATASAIDA DATETIME DEFAULT GETDATE() NOT NULL,
SAIDANOPRAZO BIT NOT NULL,
MULTA FLOAT NULL,
IDCHECKIN INT NOT NULL,
IDEMPLOYEES INT NOT NULL,
CONSTRAINT FK_CHECKOUT_CLIENTS_CHECKIN_CLIENTS FOREIGN KEY (IDCHECKIN)
REFERENCES CHECKIN_CLIENTS,
CONSTRAINT FK_CHECKOUT_CLIENTS_EMPLOYEES FOREIGN KEY (IDEMPLOYEES)
REFERENCES EMPLOYEES
)

CREATE TABLE CHECKOUT_CLIENTS_PRODUCTS_OUTPUT
(
IDCHECKOUT_CLIENTS INT NOT NULL,
IDPRODUCTS_OUTPUT INT NOT NULL,
CONSTRAINT FK_CHECKOUT_CLIENTS_PRODUCTS_OUTPUT_CHECKOUT_CLIENTS FOREIGN KEY (IDCHECKOUT_CLIENTS)
REFERENCES CHECKOUT_CLIENTS,
CONSTRAINT FK_CHECKOUT_CLIENTS_PRODUCTS_OUTPUT_PRODUCTS_OUTPUT FOREIGN KEY (IDPRODUCTS_OUTPUT)
REFERENCES PRODUCTS_OUTPUT
)

CREATE TABLE RESERVATIONS
(
ID INT PRIMARY KEY IDENTITY,
DATARESERVA DATETIME NOT NULL,
IDROOMS INT NOT NULL,
IDCLIENTS INT NOT NULL,
CONSTRAINT FK_RESERVATIONS_ROOMS FOREIGN KEY (IDROOMS)
REFERENCES ROOMS,
CONSTRAINT FK_RESERVATIONS_CLIENTS FOREIGN KEY (IDCLIENTS)
REFERENCES CLIENTS
)