CREATE TABLE EMPLOYEES 

( 

ID INT PRIMARY KEY IDENTITY, 

NOME VARCHAR(80) NOT NULL, 

CPF CHAR(11) NOT NULL, 

RG CHAR(7) NOT NULL, 

ENDERECO VARCHAR(100) NOT NULL, 

TELEFONE VARCHAR(12) NOT NULL, 

EMAIL VARCHAR(70) NOT NULL, 

SENHA VARCHAR(20) NOT NULL, 

ISADM BIT NOT NULL, 

ISATIVO BIT NOT NULL, 

CONSTRAINT UQ_EMPLOYEES_CPF UNIQUE (CPF), 

CONSTRAINT UQ_EMPLOYEES_RG UNIQUE (RG) 

) 

  

CREATE TABLE CLIENTS 

( 

ID INT PRIMARY KEY IDENTITY, 

NOME VARCHAR(80) NOT NULL, 

CPF CHAR(11) NOT NULL, 

RG CHAR(7) NOT NULL, 

TELEFONE1 VARCHAR(12) NOT NULL, 

TELEFONE2 VARCHAR(12) NULL, 

EMAIL VARCHAR(70) NOT NULL, 

CONSTRAINT UQ_CLIENTS_CPF UNIQUE (CPF), 

CONSTRAINT UQ_CLIENTS_RG UNIQUE (RG) 

) 

  

CREATE TABLE SUPPLIERS 

( 

ID INT PRIMARY KEY IDENTITY, 

RAZAOSOCIAL VARCHAR(100) NOT NULL, 

CNPJ CHAR(14) UNIQUE NOT NULL, 

NOMECONTATO VARCHAR(80) NOT NULL, 

TELEFONE VARCHAR(12) NOT NULL, 

EMAIL VARCHAR(70) NOT NULL, 

ISATIVO BIT NOT NULL, 

CONSTRAINT UQ_SUPPLIERS_CNPJ UNIQUE (CNPJ) 

) 

  

CREATE TABLE PRODUCTS 

( 

ID INT PRIMARY KEY IDENTITY, 

NOME VARCHAR(100) NOT NULL, 

DESCRICAO VARCHAR(150) NOT NULL, 

ESTOQUE FLOAT NOT NULL, 

MARGEMLUCRO FLOAT NOT NULL, 

PRECO FLOAT NOT NULL, 

ISATIVO BIT NOT NULL, 

VALIDADE DATETIME2 NOT NULL 

) 

  

CREATE TABLE STORAGE 

( 

ID INT PRIMARY KEY IDENTITY, 

IDPRODUCTS INT NOT NULL, 

QUANTIDADE FLOAT NOT NULL, 

CONSTRAINT FK_STORAGE_PRODUCTS FOREIGN KEY (IDPRODUCTS) REFERENCES PRODUCTS 

) 

  

CREATE TABLE PRODUCTS_SUPPLIERS 

( 

IDPRODUCTS INT NOT NULL, 

IDSUPPLIERS INT NOT NULL, 

CONSTRAINT FK_PRODUCTS_SUPPLIERS_PRODUCTS FOREIGN KEY (IDPRODUCTS) 

REFERENCES PRODUCTS, 

CONSTRAINT FK_PRODUCTS_SUPPLIERS_SUPPLIERS FOREIGN KEY (IDSUPPLIERS) 

REFERENCES SUPPLIERS,

PRIMARY KEY(IDPRODUCTS, IDSUPPLIERS) 

) 

  

CREATE TABLE PRODUCTS_INCOME 

( 

ID INT PRIMARY KEY IDENTITY, 

DATAENTRADA DATETIME2 NOT NULL, 

IDFUNCIONARIO INT NOT NULL, 

VALORTOTAL FLOAT NOT NULL, 

IDFORNECEDOR INT NOT NULL, 

CONSTRAINT FK_PRODUCTS_INCOME_EMPLOYEES FOREIGN KEY (IDFUNCIONARIO) 

REFERENCES EMPLOYEES, 

CONSTRAINT FK_PRODUCTS_INCOME_SUPPLIERS FOREIGN KEY (IDFORNECEDOR) 

REFERENCES SUPPLIERS 

) 

  

CREATE TABLE PRODUCTS_INCOME_DETAILS 

( 

IDPRODUCTS_INCOME INT NOT NULL, 

IDPRODUCTS INT NOT NULL, 

PRECO FLOAT NOT NULL, 

QUANTIDADE INT NOT NULL, 

CONSTRAINT FK_PRODUCTS_INCOME_DETAILS_PRODUCTS_INCOME FOREIGN KEY (IDPRODUCTS_INCOME) 

REFERENCES PRODUCTS_INCOME, 

CONSTRAINT FK_PRODUCTS_INCOME_DETAILS_PRODUCTS FOREIGN KEY (IDPRODUCTS) 

REFERENCES PRODUCTS, 

PRIMARY KEY(IDPRODUCTS_INCOME, IDPRODUCTS) 

) 

  

CREATE TABLE PRODUCTS_OUTPUT 

( 

ID INT PRIMARY KEY IDENTITY, 

DATASAIDA DATETIME2 NOT NULL, 

IDFUNCIONARIO INT NOT NULL, 

VALORTOTAL FLOAT NOT NULL, 

IDCLIENTE INT NOT NULL, 

CONSTRAINT FK_PRODUCTS_OUTPUT_EMPLOYEES FOREIGN KEY (IDFUNCIONARIO) 

REFERENCES EMPLOYEES, 

CONSTRAINT FK_PRODUCTS_OUTPUT_CLIENTS FOREIGN KEY (IDCLIENTE) 

REFERENCES CLIENTS 

) 

  

CREATE TABLE ROOMS_TYPE 

( 

ID INT PRIMARY KEY IDENTITY, 

DESCRICAO VARCHAR(100) NOT NULL, 

VALOR FLOAT NOT NULL, 

VALORDIARIA FLOAT NOT NULL, 

QTDHOSPEDES INT NOT NULL 

) 

  

CREATE TABLE ROOMS 

( 

ID INT PRIMARY KEY IDENTITY, 

ISOCUPADO BIT NOT NULL, 

NUMEROQUARTO VARCHAR(5) NOT NULL, 

DESCRICAO VARCHAR(100) NOT NULL, 

IDROOMS_TYPE INT NOT NULL, 

CONSTRAINT FK_ROOMS_ROOMSTYPE FOREIGN KEY (IDROOMS_TYPE) 

REFERENCES ROOMS_TYPE 

) 

 
CREATE TABLE CHECKIN_CLIENTS 

( 

ID INT PRIMARY KEY IDENTITY, 

DATAENTRADA DATETIME DEFAULT GETDATE() NOT NULL, 

PREVISAOSAIDA DATETIME NOT NULL, 

IDCLIENTS INT NOT NULL, 

IDROOMS INT NOT NULL, 

IDEMPLOYEES INT NOT NULL, 

CONSTRAINT FK_CHECKIN_CLIENTS_CLIENTS FOREIGN KEY (IDCLIENTS) 

REFERENCES CLIENTS, 

CONSTRAINT FK_CHECKIN_CLIENTS_ROOMS FOREIGN KEY (IDROOMS) 

REFERENCES ROOMS, 

CONSTRAINT FK_CHECKIN_CLIENTS_EMPLOYEES FOREIGN KEY (IDEMPLOYEES) 

REFERENCES EMPLOYEES 

) 

  

CREATE TABLE CHECKOUT_CLIENTS 

( 

ID INT PRIMARY KEY IDENTITY, 

DATASAIDA DATETIME DEFAULT GETDATE() NOT NULL, 

SAIDANOPRAZO BIT NOT NULL, 

MULTA FLOAT NULL, 

IDCHECKIN INT NOT NULL, 

IDEMPLOYEES INT NOT NULL, 

CONSTRAINT FK_CHECKOUT_CLIENTS_CHECKIN_CLIENTS FOREIGN KEY (IDCHECKIN) 

REFERENCES CHECKIN_CLIENTS, 

CONSTRAINT FK_CHECKOUT_CLIENTS_EMPLOYEES FOREIGN KEY (IDEMPLOYEES) 

REFERENCES EMPLOYEES 

) 

  

CREATE TABLE CHECKOUT_CLIENTS_PRODUCTS_OUTPUT 

( 

IDCHECKOUT_CLIENTS INT NOT NULL, 

IDPRODUCTS_OUTPUT INT NOT NULL, 

CONSTRAINT FK_CHECKOUT_CLIENTS_PRODUCTS_OUTPUT_CHECKOUT_CLIENTS FOREIGN KEY (IDCHECKOUT_CLIENTS) 

REFERENCES CHECKOUT_CLIENTS, 

CONSTRAINT FK_CHECKOUT_CLIENTS_PRODUCTS_OUTPUT_PRODUCTS_OUTPUT FOREIGN KEY (IDPRODUCTS_OUTPUT) 

REFERENCES PRODUCTS_OUTPUT,

PRIMARY KEY(IDCHECKOUT_CLIENTS, IDPRODUCTS_OUTPUT) 

) 

  

CREATE TABLE RESERVATIONS 

( 

ID INT PRIMARY KEY IDENTITY, 

DATARESERVA DATETIME NOT NULL, 

IDROOMS INT NOT NULL, 

IDCLIENTS INT NOT NULL, 

CONSTRAINT FK_RESERVATIONS_ROOMS FOREIGN KEY (IDROOMS) 

REFERENCES ROOMS, 

CONSTRAINT FK_RESERVATIONS_CLIENTS FOREIGN KEY (IDCLIENTS) 

REFERENCES CLIENTS 

) 

CREATE TABLE PRODUCTS_OUTPUT_DETAILS
(
IDPRODUCTS_OUTPUT INT NOT NULL,
IDPRODUCTS INT NOT NULL,
PRECO FLOAT NOT NULL,
QUANTIDADE INT NOT NULL,
PRIMARY KEY (IDPRODUCTS_OUTPUT,IDPRODUCTS),
CONSTRAINT [FK_PRODUCTS_OUTPUT_DETAILS_PRODUCTS_OUTPUT] FOREIGN KEY (IDPRODUCTS_OUTPUT) REFERENCES PRODUCTS_OUTPUT,
CONSTRAINT [FK_PRODUCTS_OUTPUT_DETAILS_PRODUCTS] FOREIGN KEY (IDPRODUCTS) REFERENCES PRODUCTS

)